...
...
output = theano.tensor.nnet.conv2d(
    input, filters, input_shape=(b, c2, i1, i2), 
filter_shape=(c1, c2, k1, k2), border_mode=(0, 0), subsample=(1, 1))
# output.shape[2] == (i1 - k1) + 1
# output.shape[3] == (i2 - k2) + 1
...
...
