...
...
#for example consider these values for a and b
# and the function f already defined
a = 1.5 
b = 2.5
...
#In this case we get c = 4.0, a floating-point value 
#stored in scalar c, another tensor
c = f(a,b)
...
...
